#include <QApplication>
#include <QObject>
#include <QAbstractNativeEventFilter>
#include <QGraphicsDropShadowEffect>
#include <QX11Info>
#include <QDesktopWidget>
#include <QResizeEvent>
#include <QFrame>
#include <QWindow>
#include <QPainter>
#include <QBitmap>
#include <QProcess>
#include <QPushButton>
#include <QBoxLayout>
#include <QLabel>
#include <xcb/xcb.h>
#include <X11/X.h>
#include <X11/Xlib.h>
#include <X11/Xatom.h>
#include <X11/Xutil.h>
#include <X11/keysym.h>
#include <X11/extensions/shape.h>

