#include <QApplication>
#include <QAbstractNativeEventFilter>
#include <QBitmap>
#include <QBoxLayout>
#include <QDesktopWidget>
#include <QHostAddress>
#include <QHBoxLayout>
#include <QFile>
#include <QFileInfo>
#include <QJsonDocument>
#include <QObject>
#include <QGraphicsDropShadowEffect>
#include <QGraphicsEffect>
#include <QResizeEvent>
#include <QFrame>
#include <QScreen>
#include <QSettings>
#include <QLocalSocket>
#include <QMetaType>
#include <QPainter>
#include <QProcess>
#include <QPushButton>
#include <QVariant>
#include <QVariantList>
#include <QVBoxLayout>
#include <QWindow>
#include <QX11Info>
#include <QLabel>
#include <xcb/xcb.h>
#include <X11/X.h>
#include <X11/Xlib.h>
#include <X11/Xatom.h>
#include <X11/Xutil.h>
#include <X11/keysym.h>
#include <X11/extensions/shape.h>

